# Generated by Django 3.2.7 on 2022-08-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(blank=True, max_length=30)),
                ('option_two', models.CharField(blank=True, max_length=30)),
                ('option_three', models.CharField(blank=True, max_length=30)),
                ('option_four', models.CharField(blank=True, max_length=30)),
                ('option_one_count', models.IntegerField(blank=True, default=0)),
                ('option_two_count', models.IntegerField(blank=True, default=0)),
                ('option_three_count', models.IntegerField(blank=True, default=0)),
                ('option_four_count', models.IntegerField(blank=True, default=0)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
