# Generated by Django 3.2.7 on 2022-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_four',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_one',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_two',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
